version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd /multi-env-vpc/frontend && npm install
  build:
    commands:
      - cd /multi-env-vpc/frontend && npm run build
  post_build:
    commands:
      - echo "current path:$(pwd)"