version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - yarn --cwd ./multi-env-vpc/frontend
  build:
    commands:
      - yarn build --cwd ./multi-env-vpc/frontend
  post_build:
    commands:
      - echo "current path:$(pwd)"