version: 0.0
os: linux
files:
  - source: /
    destination: /home/ssm-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: ssm-user
    group: ssm-user
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  ApplicationStart:
    - location: scripts/env.sh
      timeout: 60
      runas: ssm-user