version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root