version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - mkdir ./app_build && mkdir ./app_build/frontend
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/frontend
      - yarn
  build:
    commands:
      - yarn build
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/frontend/dist/* $CODEBUILD_SRC_DIR/app_build/frontend/
  post_build:
    commands:
      - echo "current path:$(pwd)"
artifacts:
  files:
    - multi-env-vpc/appspec.yml
  discard-paths: yes
  secondary-artifacts:
    artifacts1:
      files:
        - app_build/frontend/**/*
      name: secondary-artifact-name