version: 0.2

phases:
#  install:
#    runtime-versions:
#      nodejs: 12
#    commands:
#      - npm install -g yarn
  install:
    commands:
      - apt-get update && apt-get install --no-install-recommends -y curl
      - curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get update && apt-get install -y nodejs
  pre_build:
    commands:
      - echo Logging in to Amazon ECR..
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo $CODEBUILD_SRC_DIR
      - mkdir frontend-dist backend-dist scripts
  build:
    commands:
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/appspec.yml $CODEBUILD_SRC_DIR/
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/scripts/* $CODEBUILD_SRC_DIR/scripts/
      # frontend 빌드
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] FRONTEND BUILD START ..."
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/frontend
      - npm install && npm run build
      - docker build -t $FRONTEND_IMAGE_REPO_URL:latest .
      # - mv $CODEBUILD_SRC_DIR/multi-env-vpc/frontend/dist/* $CODEBUILD_SRC_DIR/frontend-dist/
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] FRONTEND BUILD FINISH"
      # backend 빌드
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND BUILD START ..."
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/backend
      - docker build -t $BACKEND_IMAGE_REPO_URL:latest .
      # - yarn && yarn build
#      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND BUILD FINISH"
#      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND TEST START ..."
#      - yarn test
#      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND TEST FINISH"
#      - mv dist node_modules package.json package-lock.json $CODEBUILD_SRC_DIR/backend-dist/
  post_build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Pushing docker images to ECR..."
      - docker push $FRONTEND_IMAGE_REPO_URL:latest
      - docker push $BACKEND_IMAGE_REPO_URL:latest
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Push Finished"
      - echo Writing image definitions file...
      - cd $CODEBUILD_SRC_DIR
      - printf '[{"name":"frontend","imageUri":"%s"},{"name":"backend","imageUri":"%s"}]' "${FRONTEND_IMAGE_REPO_URL}:latest" "${BACKEND_IMAGE_REPO_URL}:latest" | tee imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json