version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cd ./multi-env-vpc/frontend
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo "current path:$(pwd)"

artifacts:
  files:
    - multi-env-vpc/appspec.yml
    - multi-env-vpc/frontend/dist/**/*