version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - mkdir ./dist
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/frontend
      - yarn
  build:
    commands:
      - yarn build
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/appspec.yml $CODEBUILD_SRC_DIR/
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/frontend/dist/* $CODEBUILD_SRC_DIR/dist/
  post_build:
    commands:
      - echo "current path:$(pwd)"
artifacts:
  files:
    - appspec.yml
    - dist/**/*