version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cd ./multi-env-vpc/frontend
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo "current path:$(pwd)"
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - multi-env-vpc/appspec.yml
      name: appspec
      discard-paths: yes
    artifact2:
      files:
        - multi-env-vpc/frontend/dist/**/*
      name: frontend-build
      discard-paths: yes