version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - mkdir ./frontend-dist && mkdir ./backend-dist
  build:
    commands:
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/appspec.yml $CODEBUILD_SRC_DIR/
      # frontend 빌드
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] FRONTEND BUILD START ..."
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/frontend
      - yarn && yarn build
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/frontend/dist/* $CODEBUILD_SRC_DIR/frontend-dist/
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] FRONTEND BUILD FINISH"
      # backend 빌드
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND BUILD START ..."
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/backend
      - yarn && yarn build
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/backend/dist/* $CODEBUILD_SRC_DIR/backend-dist/
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND BUILD FINISH"
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND TEST START ..."
      - yarn test
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BACKEND TEST FINISH"
  post_build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] BUILD FINISH!"
artifacts:
  files:
    - appspec.yml
    - frontend-dist/**/*
    - backend-dist/**/*