version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - mkdir ./build && mkdir ./build/frontend
      - cd $CODEBUILD_SRC_DIR/multi-env-vpc/frontend
      - yarn
  build:
    commands:
      - yarn build
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/frontend/dist/* $CODEBUILD_SRC_DIR/build/frontend/
      - mv $CODEBUILD_SRC_DIR/multi-env-vpc/appspec.yml $CODEBUILD_SRC_DIR/build
  post_build:
    commands:
      - echo "current path:$(pwd)"
artifacts:
  files:
    - build/**/*